name: Test
on:
  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./node_modules
            ./packages/*/node_modules
            ./packages/*/dist
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
           npm install
           npm run build --if-present
           npm run link --if-present

  check:
    name: Check
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./node_modules
            ./packages/*/node_modules
            ./packages/*/dist
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build --if-present
          npm run link --if-present
      - run: |
          npm run lint --if-present
          npm run dep-check --if-present -- -- -- -p
          npm run dep-check --if-present -- -- -- -- --unused

  test-node:
    name: Unit tests ${{ matrix.project }} node ${{ matrix.node }} ${{ matrix.os }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [16]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.npm
            ./node_modules
            ./packages/*/node_modules
            ./packages/*/dist
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build --if-present
          npm run link --if-present
      - run: npm run test -- --since ${{ github.event.pull_request.base.sha }} --concurrency 1
